# Algortihm Parameters
alpha: 0.1
gamma: 0.8
epsilon: 0.9
epsilon_discount: 0.999 # 1098 eps to reach 0.1
nepisodes: 100000
nsteps: 1000

# Environment Parameters
desired_pose:
    x: 1.0
    y: 0.0
    z: 0.3417
desired_force: 31.57895636 # In Newtons, normal contact force when stanting still with 9.81 gravity
#3.219057733 suma de masas
desired_yaw: 0.0 # Desired yaw in radians for the hopper to stay
max_height: 4.5   # in meters
min_height: 0.0   # in meters
max_incl: 1.57       # in rads
running_step: 0.001   # in seconds
joint_increment_value: 0.5  # in radians
done_reward: -1000.0 # reward
alive_reward: 100.0 # reward

interval_reward: 100.0 # reward

weight_r1: 1.0 # Weight for joint positions ( joints in the zero is perfect )
weight_r2: 1.0 # Weight for joint efforts ( no efforts is perfect )
#weight_r3: 1.0 # Weight for contact force similar to desired ( weight of monoped )
#weight_r4: 1.0 # Weight for orientation ( vertical is perfect )
weight_r5: 1.0 # Weight for distance from desired point ( on the point is perfect ) 
weight_interval: 1.3